Created and integrated a tool to auto-generate the test example files from original example excel sheets
codeforboston/home-energy-analysis-tool pull request #213
Opened 2024-06-26 13:53 UTC by eriksynn

2024-06-26 21:05 UTC, debajyotid2 requested changes

2024-06-26 21:05 UTC, debajyotid2 commented on rules-engine/pyproject.toml
@eriksynn  You are right - `types-openpyxl` should be added to the `[project.optional-dependencies]` group in `pyproject.toml`.

2024-06-26 21:05 UTC, debajyotid2 commented on rules-engine/tests/test_rules_engine/cases/examples/shen/summary.json
@eriksynn Some of the values in `summary.json` for `shen` seem to have changed. Is it because the Excel sheet changed, or a side effect of the conversion process from the Excel workbook to the JSON and the CSV? Is this the reason why the tests fail for `shen`?

2024-06-26 23:27 UTC, eriksynn commented on rules-engine/pyproject.toml
Ok, I'm adding that now and will update the PR with the change.  Thanks for confirming that I was on the right track.

2024-06-26 23:32 UTC, eriksynn reviewed
Looks good now.  The build and tests are passing.

2024-06-26 23:34 UTC, eriksynn commented on rules-engine/tests/test_rules_engine/cases/examples/shen/summary.json
@debajyotid2 Yup, I was planning to track the shen example issue as #214.

2024-06-27 21:37 UTC, debajyotid2 approved these changes

2024-07-02 23:31 UTC, merged